### ISSUE TITLE
Trading Cryptocurrency with Elixr |> Talk

### ISSUE THREAD

**Issue by camstuart** [elixirsydney/elixirsydney#31]
### Summary

A beginner alchemists progress into automating crpto trading with visualisations. 
I have rewritten this project in a number of languages as a technology playground/test bed of sorts (Golang prior to Elixir).

The material of this talk can be somewhat flexible, Ideally a five or so minute TL;DR on the crypto trading space, and some basics on technical analysis for context. 

The project I am hacking on is Phoenix, but also has a fairly significant OTP feel, it leverages: 
- Supervisors (with a the makings of an actual supervision strategy) 
- GenServers that consume data from a websocket 
- GenServers that interact with Erlang Term Storage
- Phoenix PubSub & Live View (includes LiveView components, could potentially resolve #11)
- And some UI technologies such as Alpine.js, Tailwind UI (CSS) and Plotly.js for data visualisation

I can focus on any of these areas in greater detail, or provide a high level walk through with a view to presenting various topics in greater detail another time.

Another potential sub topic is technology trade offs with other languages and architectural considerations.

### Talk Length

~30mins, but i can talk forever about this stuff, so....
Could even break these sub topics into a lightning series?
I'll take guidance from the organisers on the best approach

### When

Any meetup is OK, or series of meetups is fine as well. 

### Twitter Handle / Avatar

@cam_stuart 

https://pbs.twimg.com/profile_images/1223421850027380736/6hUpKdym_400x400.jpg

**Comment by paulfioravanti** [comment]
Sounds great, @camstuart! As for talk length, I guess it really decides what you would like to focus on is. In order to allow multiple people to showcase their talks at the meetup, we prefer that speakers keep to about 30 minutes for full length talks, and about 5 minutes for lightning talks.

Personally, I don't mind whether you do a full-length talk, or a series of lightning talks. It really depends on how you want to divide up the information you want to convey, how you want to present it, how much time you have for preparation etc. 30 minutes probably isn't enough time to go into multiple topics in great detail, so, for example, you may want to either choose between going very deep on one or two topics, or doing high level overviews of multiple topics.

If you want any feedback on any talk you create prior to presenting, please reach out!

**Comment by camstuart** [comment]
Ok, thanks @paulfioravanti 

The approach I will go with then is a lightning series. I think this way I can keep it as Elixiry as possible.

**Series Title:**
A beginner alchemists mini series of adventures automating cryptocurrency trading.

**First Talk Title:**
From websocket data to :ets
_Capturing real time websocket data, transforming into structs and persisting in erlang term storage_

**Comment by paulfioravanti** [comment]
Okay, cool. So, we'll schedule up this lightning talk for you in August :+1:

**Comment by paulfioravanti** [comment]
Hi @camstuart, just a ping to double check you're still all good for Wednesday?

**Comment by camstuart** [comment]
Yep, I'll prep my talk tomorrow 👌

**Comment by paulfioravanti** [comment]
Thanks for your talk last week, Cam! If you end up sharing your slide deck online, please tweet out a link to them to `@elixirsydney` and we'll give it a re-tweet!
