### ISSUE TITLE
Concurrency in action

### ISSUE THREAD

**Issue by sasa1977** [elixirsydney/elixirsydney#75]
This is a redelivery of the talk I gave at YOW 2022. The talk primarily targets people new to Elixir, but more experienced developers should also find it interesting. The talk length is 40-45 minutes. I'm open to delivering it online this January. Let me know if that works for you. My social media profiles are: https://hachyderm.io/@sasajuric and https://twitter.com/sasajuric.

**Description**

Concurrent programming is a frequent source of pain and fear among software developers. Many programmers, especially more experienced ones, often say that concurrency is hard, and that it should be avoided as much as possible.

This talk aims to challenge such folklore, offering a perspective that concurrency is not inherently difficult if the tool we use is properly designed and built for the job. We'll take a look at one such tool, and explore a few real-life examples of its usage in practice.

In the process, you'll learn a bit about concurrency in BEAM, the runtime behind languages such as Erlang and Elixir. You'll also see that writing highly concurrent programs doesn't have to be very difficult, and that it can even be fun. Most importantly, you'll discover that there's a lot of potential for concurrency even in simpler programs operating at a small scale.

**Comment by joshprice** [comment]
Thanks so much Sasa! We'll get this scheduled in.

**Comment by joshprice** [comment]
We're all booked in and have just announced the meetup

**Comment by paulfioravanti** [comment]
Hi, @sasa1977! Just confirming that you're still okay to go for the meetup next Wednesday. Is there anything else we can help with, or information we can provide? I'm sure you've already seen it, but the promotion tweet for the meetup is here: https://twitter.com/ElixirSydney/status/1613687428954599429

**Comment by sasa1977** [comment]
> Is there anything else we can help with, or information we can provide?

Some instructions on where & when to join for streaming would be helpful :-)

**Comment by paulfioravanti** [comment]
Sure thing! The meetup page itself is [here](https://www.meetup.com/elixir-sydney/events/289239993/).

The link to the Zoom meeting we'll use is [here](https://us02web.zoom.us/j/87500156603?pwd=T0U2cTVlS01USVFtY0NJNmxUSGJFZz09). The meetup itself will start at the venue on Wed, Jan 18 at 6 p.m. AEDT, and we expect we'll get started by 6:30 p.m AEDT.

The Zoom meeting will be open much earlier than the meetup start time since we'll be doing a lot of tech checking to make sure everything works as expected at the venue. So, feel free to join before the start time so we can do your tech checking as well.

Talks are recorded and released on the [Elixir Australia YouTube channel](https://www.youtube.com/@ElixirAustralia).

If I've missed anything, please let me know!

**Comment by paulfioravanti** [comment]
Thanks very much for coming along and giving your talk, @sasa1977! The YouTube link to the video is [here](https://www.youtube.com/watch?v=NNAf2AXBpik).
